set_property SRC_FILE_INFO {cfile:E:/ZYNQcode/PS/GPIO_AXI/GPIO_AXI.srcs/constrs_1/new/GPIO_AXI.xdc rfile:../../../GPIO_AXI.srcs/constrs_1/new/GPIO_AXI.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_io[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {gpio_rtl_0_tri_io[0]}]
